version: "3.7"

services:
  db:
    image: postgres
    restart: always
    networks:
      - container_net
    ports:
      - 5432:5432
    env_file:
      - .env
  server:
    ports:
      - 3000:3000
    networks:
      - container_net
    build: .
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/app
  frontend:
    ports:
      - 80:3000
    networks:
      - container_net
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./frontend:/app
    build:
      context: .
      dockerfile: Dockerfile.frontend
networks:
  container_net:
    external: true
    name: container_net
