version: "3.7"

services:
  server:
    ports:
      - 3000:3000
    networks:
      - container_net
    build:
      context: .
      dockerfile: backend.dockerfile
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    restart: always
    networks:
      - container_net
    ports:
      - 5432:5432
    env_file:
      - .env

  frontend:
    image: frontend
    restart: always
    networks:
      - container_net
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: frontend.dockerfile
    depends_on:
      - server

networks:
  container_net:
    external: true
    name: container_net
