"""empty message

Revision ID: f9826841b831
Revises: 4e22875b7c8c
Create Date: 2022-07-17 05:12:53.912111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9826841b831'
down_revision = '4e22875b7c8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('address', sa.String(length=255), server_default='улица Неизвестная 1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'address')
    # ### end Alembic commands ###
